"""Ajout de user_type à History

Revision ID: f69415814ec8
Revises: 674ee37a032e
Create Date: 2025-04-21 16:11:01.521257

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f69415814ec8'
down_revision = '674ee37a032e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_type', sa.String(length=50), nullable=False))
        batch_op.alter_column('action',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=False)
        batch_op.drop_constraint('history_ibfk_1', type_='foreignkey')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('history', schema=None) as batch_op:
        batch_op.create_foreign_key('history_ibfk_1', 'user', ['user_id'], ['id'])
        batch_op.alter_column('action',
               existing_type=sa.Text(),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=False)
        batch_op.drop_column('user_type')

    # ### end Alembic commands ###
